// Generated by Selenium IDE

import org.junit.jupiter.api.Test;

public class ContactCreationTests extends TestBase {

    @Test
    public void canCreateContact() {
        openContactsPage();
        createContact("name", "last name");
    }

    @Test
    public void canCreateContactWithEmptyName() {
        openContactsPage();
        createContact("", "");
    }

    @Test
    public void canCreateContactWithNameOnly() {
        openContactsPage();
        createContact("some name", "");
    }
}
