// Generated by Selenium IDE

import org.junit.jupiter.api.Test;

public class ContactRemovalTests extends TestBase {

    @Test
    public void canRemoveContact() {
        openContactsPage();
        if (!isContactPresent()) {
            createContact("Anvar", "Serojitdinov");
        }

        removeContact();
    }
}
