package tests;// Generated by Selenium IDE

import model.ContactData;
import org.junit.jupiter.api.Test;

public class ContactRemovalTests extends TestBase {

    @Test
    public void canRemoveContact() {
        if (!app.contacts().isContactPresent()) {
            app.contacts().createContact(new ContactData("Anvar", "Serojitdinov", "167 Church street", "grande@yopmail.com", "6475996758"));
        }
        app.contacts().removeContact();
    }
}
